version: '3.8'
services:
  db-first-api:
    image: postgres:13
    container_name: db-first-api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=first_api
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./docker/database/pg_hba.conf:/etc/postgresql/13/main/pg_hba.conf

  db-first-api-testing:
    image: postgres:13
    container_name: db-first-api-testing
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DATABASE=first_api_testing
    ports:
        - '5434:5432'

volumes:
    app-volume: #
